config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#index"
  get "user/new", to: "users#new", as: "new_user"
  get "user/:id", to: "users#show", as: "show_user"
  get "user/edit/:id", to: "users#edit", as: "edit_user"
  get "user/delete/:id", to: "users#destroy", as: "delete_user"

  post "user/new", to: "users#create"
  patch "user/edit/:id", to: "users#edit_user"
  delete "user/delete/:id", to: "users#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_rich_text :description
  belongs_to :department
  belongs_to :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy, :edit_user] # rubocop:disable Layout/SpaceInsideArrayLiteralBrackets
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to root_path()
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "User deleted successfully."
  end

  def edit_user
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:firstName, :lastName, :phone, :age, :description, :gender, :address, :salary, :occupation, :birthdate, :country_id, :department_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def select_country
    Country.all
  end

  def select_department
    Department.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Table Data" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
Edit User

<%= form_with model: @user, url: edit_user_path(@user), method: :patch  do |f| %>
    <div>
        <label>First Name</label>
        <%= f.text_field :firstName %>
    </div>
    <div>
        <label>Last Name</label>
        <%= f.text_field :lastName %>
    </div>
    <div>
        <label>Phone Number</label>
        <%= f.text_field :phone %>
    </div>
    <div>
        <label>Age</label>
        <%= f.text_field :age %>
    </div>
    <div>
        <label>Gender</label>
        <%= f.radio_button :gender, "Male" %> Male
        <%= f.radio_button :gender, "Female" %> Female
    </div>
    <div>
        <label>Address</label>
        <%= f.text_field :address %>
    </div>
    <div>
        <label>Salary</label>
        <%= f.text_field :salary %>
    </div>
    <div>
        <label>Occupation</label>
        <%= f.text_field :occupation %>
    </div>
    <div>
        <label>BirthDay</label>
        <%= f.date_field :birthdate %>
    </div>
    <div>
        <label>Country</label>
        <%= f.select :country_id, options_from_collection_for_select(select_country, 'id', 'name', f.object.country_id), { include_blank: "Select Country" } %>
    </div>
    <div>
        <label>Department</label>
        <%= f.select :department_id, options_from_collection_for_select(select_department, 'id', 'name', f.object.department_id), { include_blank: "Select Country" } %>
    </div>
    <div>
        <label>Description</label>
        <%= f.rich_text_area :description %>
    </div>
    <%= f.submit "Submit"%>
    <%= link_to "back", root_path %>
<% end %>

app/views/users/index.html.erb
<% if @users.exists? %>
  hey all users

  <%= link_to 'Create a new user', new_user_path() %>
  <table>
    <tr>
      <th>Name</th>
      <th>Phone Number</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Salary</th>
      <th>Occupation</th>
      <th>Address</th>
      <th>BirthDate</th>
      <th>Department</th>
      <th>Country</th>
      <th>Description</th>
      <th></th>
    </tr>
      <% @users.each do |user| %>
          <tr>
              <td> <%= user.firstName%> <%= user.lastName %>  </td>
              <td> <%= user.phone %> </td>
              <td> <%= user.age %> </td>
              <td> <%= user.gender %> </td>
              <td> <%= user.salary %> </td>
              <td> <%= user.occupation %> </td>
              <td> <%= user.address %> </td>
              <td> <%= user.birthdate %> </td>
              <td> <%= user.department&.name || 'No Department Selected' %> </td>
              <td> <%= user.country&.name || 'No Country Selected' %> </td>
              <td> <%= user.description %> </td>
              <td> <%= link_to "Delete", delete_user_path(user.id), method: :delete  %> | <%= link_to "show user", show_user_path(user.id)  %> | <%= link_to "Edit User", edit_user_path(user.id)  %></td>
          </tr>
      <% end %>
  </table>
<% else %>
  <h1> No Data   <%= link_to 'Click to Create a new user', new_user_path() %></h1>
<% end %>

app/views/users/new.html.erb
create new user

<%= form_with  model: @user, url: new_user_path(@user), method: :post  do |f| %>
    <div>
        <label>First Name</label>
        <%= f.text_field :firstName %>
    </div>
    <div>
        <label>Last Name</label>
        <%= f.text_field :lastName %>
    </div>
    <div>
        <label>Phone Number</label>
        <%= f.text_field :phone %>
    </div>
    <div>
        <label>Age</label>
        <%= f.text_field :age %>
    </div>
    <div>
        <label>Gender</label>
        <%= f.radio_button :gender, "Male" %> Male
        <%= f.radio_button :gender, "Female" %> Female
    </div>
    <div>
        <label>Address</label>
        <%= f.text_field :address %>
    </div>
    <div>
        <label>Salary</label>
        <%= f.text_field :salary %>
    </div>
    <div>
        <label>Occupation</label>
        <%= f.text_field :occupation %>
    </div>
    <div>
        <label>BirthDay</label>
        <%= f.date_field :birthdate %>
    </div>
    <div>
        <label>Country</label>
        <%= f.select :country_id, options_from_collection_for_select(select_country, 'id', 'name'), { include_blank: 'Select Country'} %>
    </div>
    <div>
        <label>Department</label>
        <%= f.select :department_id, options_from_collection_for_select(select_department, 'id', 'name'), { include_blank: 'Select Department'} %>
    </div>
    <div>
        <label>Description</label>
        <%= f.rich_text_area :description %>
    </div>
    <%= f.submit "Submit"%>
        <%= link_to "back", root_path %>
<% end %>

app/views/users/show.html.erb
<%= @user.id %>
<%= @user.firstName %>
<%= @user.lastName %>